DROP TABLE employee IF EXISTS;
 
CREATE TABLE USER  (
    USER_ID VARCHAR(50) NOT NULL PRIMARY KEY,
    USER_NO VARCHAR(20) NOT NULL,
    USER_PASSWORD VARCHAR(50) NOT NULL,
    FAILED_COUNT INTEGER DEFAULT 0
);